### ISSUE TITLE
Use components from `@shootismoke/ui`

### ISSUE THREAD

**Issue by amaurymartiny** [amaurymartiny/shoot-i-smoke#632]
We're working on the [webapp](https://github.com/shootismoke/webapp) now, so I decided to extract some components out for easy re-use, they are in https://github.com/shootismoke/common/tree/master/packages/ui.

However some components are not replaced yet inside this repo:
- [x] CigarettesBlock (done in #620)
- [x] BoxButton (done in #680)
- [x] Button (done in #754)
- [ ] AboutBox (renamed to ConversionBox)

This issue is removing these components from this repo, and using the ones from `@shootismoke/ui` instead.

**Comment by jorgerivero3** [comment]
#680

**Comment by lomby92** [comment]
Found by searching for `hacktoberfest`, i will take care of replacing `Button`.

**Comment by lomby92** [comment]
@amaurymartiny  I can also do the AboutBox replacing, let me know if you are ok with this

**Comment by amaurymartiny** [comment]
Yes, please, go ahead! 🙏

**Comment by lomby92** [comment]
PR for ConversionBox: https://github.com/amaurymartiny/shoot-i-smoke/pull/755
